addons:
  apt:
    packages:
      - xvfb

before_install:
  - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis]" ; then echo "[skip travis] has been found, exiting" && exit 0 ; else echo "[skip travis] has not been found, continuing" ; fi

language: python
python: 3.6

install:
  - pip install -U tox
  - export TOXENV=py${TRAVIS_PYTHON_VERSION//./}
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - set
  - echo 'Home dir is: '
  - echo ${HOME}

script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dotz
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: mpasternak/amms-planop2xls
    condition: $TOXENV == py27
