language: python
python: 3.6

install:
  - pip install -U tox
  - export TOXENV=${TRAVIS_PYTHON_VERSION//./}

script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dotz
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: mpasternak/amms-planop2xls
    condition: $TOXENV == py27
