language: python
python: 3.6

install:
  - pip install -U tox pyqt_distutils==0.7.2
  - export TOXENV=py${TRAVIS_PYTHON_VERSION//./}

script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dotz
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: mpasternak/amms-planop2xls
    condition: $TOXENV == py27
